name: Security Scan
on: [push]

jobs:
  checkov-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run Checkov (SAST)
        uses: bridgecrewio/checkov-action@master
        with:
          directory: .
          framework: all
          soft_fail: true